[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0-alpha.2"  # 外部包 crates.io

[profile.dev]
panic = 'unwind'
opt-level = 0   # 编译时的代码优化程度

[profile.release]
panic = 'abort'